config/routes.rb
Maitredj::Application.routes.draw do
  
  resources :songs

  resources :checkins

  resource :user

	scope module: 'clients' do
		resources :foursquare_clients, only: ['new'], path: 'clients/foursquare' do
		  collection do
		    get 'callback'
		  end
		end
	end

  resources :songs

  match 'push' => 'push#index'
  root :to => 'users#new'
  match 'display' => 'root#index'

end

app/models/foursquare_client.rb
# https://developer.foursquare.com/docs/
class FoursquareClient
  attr_accessor :access_token

  def initialize(access_token)
    @access_token = access_token
  end

  def user_info
    @user_info ||= get('users/self').parsed['response']['user']
  end

  def user_id
    user_info['id']
  end

  def user_name
    [user_info['firstName'], user_info['lastName']].join(' ')
  end

  def oauth2_token
    @oauth2_token ||= OAuth2::AccessToken.from_hash(self.class.oauth2_client, {access_token: access_token}.merge(mode: :query, param_name: 'oauth_token'))
  end

  def get(path, params = {})
    oauth2_token.get(self.class.endpoint + path, params)
  end

  def post(path, params = {})
    oauth2_token.post(self.class.endpoint + path, params)
  end

  def create_checkin_reply(checkin_id, options = {})
    post("checkins/#{checkin_id}/reply", params: options)
  end

	class << self
    def endpoint
      'https://api.foursquare.com/v2/'
    end

    def oauth2_client
      options = {
        authorize_url: 'https://foursquare.com/oauth2/authenticate',
        token_url:     'https://foursquare.com/oauth2/access_token',
        raise_errors:  true,
      }
      OAuth2::Client.new("YLCVER0A3YY0OEXGSNV0N1DEF1D5YD0RLN24VCSXCRNWFWTJ", "CREIAI44G5GHMMMVGV0JDVOQ214I0LXTK13TEAAYNUKK3BZV", options)
    end
  end
end

app/models/foursquare_user.rb
class FoursquareUser < ActiveRecord::Base
  def name
    client.user_name
  end

  def client
    @client ||= FoursquareClient.new(access_token)
  end

  class << self
    def find_or_create_by_access_token(access_token)
      client = FoursquareClient.new(access_token)

      unless user = self.find_by_foursquare_id(client.user_id)
        user = self.new
        user.foursquare_id = client.user_id
        user.access_token = client.access_token
        user.save!
      end
      user
    end
  end
end

app/models/song.rb
class Song < ActiveRecord::Base
  attr_accessible :query, :venue
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  def default_url_options
    if Rails.env.production?
      {:host => "maitredj.herokuapp.com"}
    else  
      {:host => "localhost:3000"}
    end
  end
end

app/controllers/checkins_controller.rb
class CheckinsController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def create
    checkin = JSON.parse(params['checkin'])
    # TODO: verify push secret
    user = FoursquareUser.find_by_foursquare_id(checkin['user']['id'])
    user.client.create_checkin_reply(checkin['id'], text: "hello world!")
    return head :ok
  end
end

app/controllers/clients/foursquare_clients_controller.rb
class Clients::FoursquareClientsController < ApplicationController
	def new
		# https://developer.foursquare.com/overview/auth
		options = {
		  redirect_uri: callback_foursquare_clients_url,
		}
		redirect_to client.auth_code.authorize_url options
	end

	def callback
		if params[:error]
			debugger
			logger.error(params[:error])
		end
		token = client.auth_code.get_token params[:code], redirect_uri: callback_foursquare_clients_url
		user = FoursquareUser.find_or_create_by_access_token(token.token)

		Rails.cache.write(user.foursquare_id, token.token)
		
		logger.info 'WRITTEN TO GLOBAL HACKS'
		logger.info user.foursquare_id 
		logger.info token.token

		session[:user_id] = user.id
		redirect_to user_path
	end

	private
	def client
	  FoursquareClient.oauth2_client
	end
end

app/controllers/push_controller.rb
require 'uri'
require 'net/http'

class PushController < ApplicationController
	def index
		@event=JSON.parse(URI.unescape(params[:checkin]))
		logger.info("Event:"+@event.inspect)
		#@event=JSON.parse(request.body.read)
		checkin_id=@event['id']
		logger.info("ID"+checkin_id.inspect)
		uri = URI.parse("https://api.foursquare.com/v2/checkins/"+checkin_id+"/reply")

		# Shortcut
		req = Net::HTTP::Post.new(uri.path)
		req.set_form_data({'url'=>new_song_url, 'text' => 'hello world', 'oauth_token' => Rails.cache.read(@event['user']['id'])})
		http = Net::HTTP.new(uri.host, uri.port)
		http.use_ssl = true
		response = http.request(req)
		logger.info("Response:"+response.inspect)

		logger.info("CHECKIN_ID:"+checkin_id.inspect)
		logger.info("URI:"+uri.inspect)
		logger.info("URL:"+new_song_url.inspect)

		logger.info("BODY:" + response.body.inspect)

		render :text => 'OK'
	end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.order('created_at ASC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @songs }
    end

    @songs.delete_all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    @song = Song.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/new
  # GET /songs/new.json
  def new
    @song = Song.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/1/edit
  def edit
    @song = Song.find(params[:id])
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(params[:song])

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render json: @song, status: :created, location: @song }
      else
        format.html { render action: "new" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /songs/1
  # PUT /songs/1.json
  def update
    @song = Song.find(params[:id])

    respond_to do |format|
      if @song.update_attributes(params[:song])
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def show
  end

  private
  def current_user
    @current_user ||= FoursquareUser.find(session[:user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/push_helper.rb
module PushHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/song_helper.rb
module SongHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JAMSESH</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.4.3/underscore-min.js" %>
  <script src="http://www.youtube.com/player_api"></script>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= @custom_head.html_safe if @custom_head %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/root/index.html.haml
#queue
= javascript_tag 'window.rootpagething = true;'
<div id="player" width="100%" height="100%">
</div>
<!--#player-->
<script type="text/javascript" src="//use.typekit.net/wts2npf.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :venue %><br />
    <%= f.text_field :venue %>
  </div>
  <div class="field">
    <%= f.label :query %><br />
    <%= f.text_field :query %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<h1>Listing songs</h1>

<table>
  <tr>
    <th>Venue</th>
    <th>Query</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @songs.each do |song| %>
  <tr>
    <td><%= song.venue %></td>
    <td><%= song.query %></td>
    <td><%= link_to 'Show', song %></td>
    <td><%= link_to 'Edit', edit_song_path(song) %></td>
    <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Song', new_song_path %>

app/views/songs/new.html.haml
- @custom_head = '<meta name="viewport" content="width=320, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />'

<script type="text/javascript" src="//use.typekit.net/wts2npf.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>

<h1>ENTER A SONG NAME AND SUBMIT!</h1>

= form_for(@song) do |f|
  = f.text_field :query
  %br
  = f.submit 'ADD SONG'

app/views/songs/show.html.erb
<% @custom_head = '<meta name="viewport" content="width=320, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />' %>

<script type="text/javascript" src="//use.typekit.net/wts2npf.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>

<h1>THANKS! WE'LL PLAY YOUR SONG SOON :)</h1>

app/views/users/new.html.haml
- @custom_head = '<meta name="viewport" content="width=320, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />'

<script type="text/javascript" src="//use.typekit.net/wts2npf.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>


<h1>CONNECT <span style="color:#0f0">JAMSESH</span> TO YOUR FOURSQUARE!!!</h1>

<a href='#{new_foursquare_client_path}'><img style='margin-left:auto;margin-right:auto;width:300px;display:block;' src='https://playfoursquare.s3.amazonaws.com/press/logo/connect-white@2x.png' /></a>

app/views/users/show.html.haml
- @custom_head = '<meta name="viewport" content="width=320, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />'

<script type="text/javascript" src="//use.typekit.net/wts2npf.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>

<h1><span style="color:#0f0">GOOD JOB.</span> NOW GO CHECK IN SOMEWHERE!</h1>